name: Generate Artifact

on:
  repository_dispatch:
    types: [start_regression_tests]

jobs:
  build-and-generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.branch }}

      - name: List Files in Main Repo Folder
        run: |
          echo "Listing files in the main repository folder:"
          ls -la

      - name: Build Project
        run: |
          # Add commands to build your project here
          echo "Building project on branch ${{ github.event.client_payload.branch }}"

      - name: Generate Artifact
        run: |
          # Replace with your artifact generation steps
          echo "Generated artifact content" > test_status.txt
        shell: bash

      - name: Upload Test Status Artifact
        uses: actions/upload-artifact@v4
        with:
          name: success_${{ github.event.client_payload.run_id }}_${{ github.run_id }}
          path: test_status.txt