name: Second Workflow

on:
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run some tests
        run: |
          echo "Running tests"
          # Simulate test outcome
          echo "Test outcome: success"
          TEST_STATUS="success"

      - name: Notify First Workflow
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          curl -X POST -H "Authorization: token $GH_TOKEN" \
               -H "Accept: application/vnd.github.everest-preview+json" \
               https://api.github.com/repos/${{ github.repository }}/dispatches \
               -d '{"event_type":"notify-first-workflow","client_payload":{"status":"'"$TEST_STATUS"'"}}'
