name: Second Workflow

on:
  repository_dispatch:
    types: [start_regression_tests]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run some tests
        run: |
          echo "Running tests"
          TEST_STATUS="success"  # Simulate test outcome

      - name: Notify First Workflow with Static Payload
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          curl -X POST -H "Authorization: token $GH_TOKEN" \
               -H "Accept: application/vnd.github.everest-preview+json" \
               https://api.github.com/repos/${{ github.repository }}/dispatches \
               -d '{"event_type":"notify-first-workflow","client_payload":{"status":"static-success"}}'