name: Generate Artifact

on:
  workflow_dispatch:
    inputs:
      param1:
        description: "An example input parameter"
        required: true

jobs:
  build-and-generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Project
        run: |
          # Add commands to build your project here
          echo "Building project..."

      - name: Generate Artifact
        run: |
          # Replace with your artifact generation steps
          mkdir -p artifacts
          echo "Generated artifact content" > artifacts/desired_artifact_name.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: desired_artifact_name
          path: artifacts/desired_artifact_name.txt
